# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7e6be8d4d6b0e935657df5dc485ec8b54a35f167e37ea47306958cd1e34f64eb7343e399e24fc30b64f00b7456ae6f63faa9e4b227d7c693bd8c2a26cd1b6390

test:
  secret_key_base: d95371861075a48313bdca47c789f9558ab922149566bb4d69241de0c30c224f5d3659d86312b5c1c427b11f3a184fc0eaa1b3a5a563bb6c14f3392ca194031b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
